# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11system_info.proto\"5\n\x11SystemInfoRequest\x12 \n\x0b\x63lient_info\x18\x01 \x01(\x0b\x32\x0b.ClientInfo\"X\n\x12SystemInfoResponse\x12 \n\x0b\x63lient_info\x18\x01 \x01(\x0b\x32\x0b.ClientInfo\x12 \n\x0bserver_info\x18\x02 \x01(\x0b\x32\x0b.ServerInfo\"*\n\nClientInfo\x12\x1c\n\thost_info\x18\x01 \x01(\x0b\x32\t.HostInfo\"*\n\nServerInfo\x12\x1c\n\thost_info\x18\x01 \x01(\x0b\x32\t.HostInfo\"N\n\x08HostInfo\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x0f\n\x07ip_addr\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\x32\x45\n\nSystemInfo\x12\x37\n\nSystemInfo\x12\x12.SystemInfoRequest\x1a\x13.SystemInfoResponse\"\x00\x62\x06proto3')



_SYSTEMINFOREQUEST = DESCRIPTOR.message_types_by_name['SystemInfoRequest']
_SYSTEMINFORESPONSE = DESCRIPTOR.message_types_by_name['SystemInfoResponse']
_CLIENTINFO = DESCRIPTOR.message_types_by_name['ClientInfo']
_SERVERINFO = DESCRIPTOR.message_types_by_name['ServerInfo']
_HOSTINFO = DESCRIPTOR.message_types_by_name['HostInfo']
SystemInfoRequest = _reflection.GeneratedProtocolMessageType('SystemInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMINFOREQUEST,
  '__module__' : 'system_info_pb2'
  # @@protoc_insertion_point(class_scope:SystemInfoRequest)
  })
_sym_db.RegisterMessage(SystemInfoRequest)

SystemInfoResponse = _reflection.GeneratedProtocolMessageType('SystemInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMINFORESPONSE,
  '__module__' : 'system_info_pb2'
  # @@protoc_insertion_point(class_scope:SystemInfoResponse)
  })
_sym_db.RegisterMessage(SystemInfoResponse)

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'system_info_pb2'
  # @@protoc_insertion_point(class_scope:ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

ServerInfo = _reflection.GeneratedProtocolMessageType('ServerInfo', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO,
  '__module__' : 'system_info_pb2'
  # @@protoc_insertion_point(class_scope:ServerInfo)
  })
_sym_db.RegisterMessage(ServerInfo)

HostInfo = _reflection.GeneratedProtocolMessageType('HostInfo', (_message.Message,), {
  'DESCRIPTOR' : _HOSTINFO,
  '__module__' : 'system_info_pb2'
  # @@protoc_insertion_point(class_scope:HostInfo)
  })
_sym_db.RegisterMessage(HostInfo)

_SYSTEMINFO = DESCRIPTOR.services_by_name['SystemInfo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYSTEMINFOREQUEST._serialized_start=21
  _SYSTEMINFOREQUEST._serialized_end=74
  _SYSTEMINFORESPONSE._serialized_start=76
  _SYSTEMINFORESPONSE._serialized_end=164
  _CLIENTINFO._serialized_start=166
  _CLIENTINFO._serialized_end=208
  _SERVERINFO._serialized_start=210
  _SERVERINFO._serialized_end=252
  _HOSTINFO._serialized_start=254
  _HOSTINFO._serialized_end=332
  _SYSTEMINFO._serialized_start=334
  _SYSTEMINFO._serialized_end=403
# @@protoc_insertion_point(module_scope)
