# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\"\x14\n\x12HealthCheckRequest\"\x90\x01\n\x13HealthCheckResponse\x12\x36\n\x0bstatus_code\x18\x01 \x01(\x0e\x32!.HealthCheckResponse.HealthStatus\x12\x0e\n\x06status\x18\x02 \x01(\t\"1\n\x0cHealthStatus\x12\x06\n\x02OK\x10\x00\x12\x19\n\x15UNKNOWN_HEALTH_STATUS\x10\x01\x32\x44\n\x06Health\x12:\n\x0bHealthCheck\x12\x13.HealthCheckRequest\x1a\x14.HealthCheckResponse\"\x00\x62\x06proto3')



_HEALTHCHECKREQUEST = DESCRIPTOR.message_types_by_name['HealthCheckRequest']
_HEALTHCHECKRESPONSE = DESCRIPTOR.message_types_by_name['HealthCheckResponse']
_HEALTHCHECKRESPONSE_HEALTHSTATUS = _HEALTHCHECKRESPONSE.enum_types_by_name['HealthStatus']
HealthCheckRequest = _reflection.GeneratedProtocolMessageType('HealthCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKREQUEST,
  '__module__' : 'health_pb2'
  # @@protoc_insertion_point(class_scope:HealthCheckRequest)
  })
_sym_db.RegisterMessage(HealthCheckRequest)

HealthCheckResponse = _reflection.GeneratedProtocolMessageType('HealthCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKRESPONSE,
  '__module__' : 'health_pb2'
  # @@protoc_insertion_point(class_scope:HealthCheckResponse)
  })
_sym_db.RegisterMessage(HealthCheckResponse)

_HEALTH = DESCRIPTOR.services_by_name['Health']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEALTHCHECKREQUEST._serialized_start=16
  _HEALTHCHECKREQUEST._serialized_end=36
  _HEALTHCHECKRESPONSE._serialized_start=39
  _HEALTHCHECKRESPONSE._serialized_end=183
  _HEALTHCHECKRESPONSE_HEALTHSTATUS._serialized_start=134
  _HEALTHCHECKRESPONSE_HEALTHSTATUS._serialized_end=183
  _HEALTH._serialized_start=185
  _HEALTH._serialized_end=253
# @@protoc_insertion_point(module_scope)
